'use client';

import { useEffect, useRef } from 'react';
import Link from 'next/link';
import UXUIDCNavigation from '@/components/UXUIDC/Navigation';
import UXUIDCFooter from '@/components/UXUIDC/Footer';
import UXUIDCAnimatedFAQ from '@/components/UXUIDC/AnimatedFAQ';
import UXUIDCAnimatedCounter from '@/components/UXUIDC/AnimatedCounter';
import LabSignalsSignup from '@/components/UXUIDC/LabSignalsSignup';
import { IconDNA, IconQuote, IconChevronRight, IconCheckCircle } from '@/components/UXUIDC/Icons';
import { GlossaryTermLink } from '@/components/UXUIDC';

// Hero Data
const heroData = {
  badge: "BAC Transgenics & ROSA26",
  title: "Transgenic Mouse Models",
  intro: "Since 1998, ingenious targeting laboratory has completed over 2,500 custom gene targeting projects for researchers at universities, pharmaceutical companies, and research institutions worldwide. Our mouse models have supported research published in more than 800 peer reviewed articles including in Science, Nature, and Cell.",
  description: "Transgenic mouse models introduce exogenous DNA sequences into the mouse genome for overexpression studies, tissue specific Cre driver generation, reporter line creation, and other applications requiring expression of non native sequences. Unlike knockin models that modify endogenous loci, transgenic approaches add new genetic elements either through random integration or targeted insertion at safe harbor loci."
};

// Stats Data
const statsData = [
  { value: 2500, suffix: "+", label: "Projects Completed" },
  { value: 800, suffix: "+", label: "Publications" },
  { value: 26, suffix: "+", label: "Years Experience" },
  { value: 100, suffix: "%", label: "Success Guarantee" }
];

// Transgenic Approaches
const transgenicApproaches = [
  {
    title: "Conventional Transgenesis",
    description: "Conventional transgenic mice are generated by pronuclear injection of DNA constructs into fertilized oocytes. The transgene integrates randomly into the genome, typically as a multi copy array. This approach is rapid and cost effective for applications where precise copy number and integration site are not critical.",
    useCase: "Commonly used for overexpression studies, generation of multiple founder lines for comparison, and applications where high expression levels are desired."
  },
  {
    title: "BAC Transgenesis",
    description: "BAC (bacterial artificial chromosome) transgenic mice carry large genomic fragments up to 200 kb, including the gene of interest with its native regulatory elements. BAC transgenics often show more physiological expression patterns than conventional transgenics because distant enhancers and regulatory regions are preserved.",
    useCase: "Particularly valuable for generating Cre driver lines where accurate tissue specific expression is essential."
  },
  {
    title: "ROSA26 Targeted Transgenics",
    description: "ROSA26 targeted transgenics insert transgene constructs at the ROSA26 safe harbor locus. This approach provides single copy integration at a defined genomic location with predictable expression characteristics.",
    useCase: "Eliminates the positional effects common with random integration and ensures consistent expression across breeding generations.",
    link: "/rosa26"
  },
  {
    title: "Other Safe Harbor Loci",
    description: "In addition to ROSA26, transgenes can be targeted to other safe harbor loci including HPRT and H11. Each locus offers distinct expression characteristics and can be selected based on desired expression levels and tissue distribution."
  }
];

// Applications
const applicationsData = [
  {
    title: "Cre Driver Lines",
    description: "Transgenic Cre driver lines express Cre recombinase under tissue specific promoters, enabling conditional gene manipulation when crossed to floxed alleles. At Ingenious, Cre drivers can be targeted to the ROSA26 locus or to an endogenous gene of interest.",
    link: "/tissue-specific-cre-lines"
  },
  {
    title: "Reporter Lines",
    description: "Transgenic reporter lines express visualization markers under constitutive or tissue specific promoters. Common reporters include fluorescent proteins for live imaging, luciferase for bioluminescence studies, and LacZ for histological analysis. ROSA26 targeted reporters provide consistent expression and can be designed as Cre dependent systems for lineage tracing applications."
  },
  {
    title: "Inducible Expression Systems",
    description: "Transgenic mice carrying inducible expression systems allow controlled activation of transgene expression.",
    systems: [
      { name: "Tet On / Tet Off", desc: "Doxycycline regulated expression" },
      { name: "CreERT2", desc: "Tamoxifen inducible Cre expression" },
      { name: "Cre dependent", desc: "Expression activated by Cre mediated removal of stop cassette" }
    ],
    link: "/tamoxifen-inducible-cre"
  }
];

// Targeted Integration Advantages
const targetedAdvantages = [
  "Single copy integration at defined locus",
  "Predictable expression characteristics",
  "No founder to founder variation",
  "Stable expression across generations",
  "No risk of insertional mutagenesis"
];

// Publications Data
// Publications Data - Verified with PubMed links (January 2026)
const publicationsData = [
  {
    authors: "Jiang Y, Sachdeva K, Goulbourne CN, Berg MJ, Peddy J, Stavrides PH, et al.",
    year: "2025",
    title: "Increased neuronal expression of the early endosomal adaptor APPL1 leads to endosomal and synaptic dysfunction with cholinergic neurodegeneration.",
    journal: "J Neurosci",
    volume: "45(29): e2331242025",
    link: "https://pubmed.ncbi.nlm.nih.gov/40514243/"
  },
  {
    authors: "Clausen BE et al.",
    year: "1999",
    title: "Conditional gene targeting in macrophages and granulocytes using LysMcre mice.",
    journal: "Transgenic Research",
    volume: "8(4): 265-277",
    link: "https://pubmed.ncbi.nlm.nih.gov/10621974/"
  }
];

// Testimonial Data
// Verified testimonials from master data - https://www.genetargeting.com/testimonials
import { getTestimonialById, formatAuthorWithCredentials } from '@/data/verifiedTestimonials';

const bosmansTestimonial = getTestimonialById('bosmans-ghent')!;

const testimonials = [
  { quote: bosmansTestimonial.quote, name: formatAuthorWithCredentials(bosmansTestimonial), affiliation: bosmansTestimonial.affiliation },
];

// Related Links
const transgenicServices = [
  { title: "ROSA26", href: "/rosa26" },
  { title: "Tissue Specific Cre Lines", href: "/tissue-specific-cre-lines" },
  { title: "Cre Driver Catalog", href: "/cre-driver-catalog" }
];

const relatedModelTypes = [
  { title: "Knockin Mouse Models", href: "/knockin-mouse-models" },
  { title: "Knockout Mouse Models", href: "/knockout-mouse-models" },
  { title: "Conditional Knockout Mouse Models", href: "/conditional-knockout-mouse-models" },
  { title: "Reporter Knockin", href: "/reporter-knockin" }
];

const relatedTechnologies = [
  { title: "Cre Lox System", href: "/cre-lox-system" },
  { title: "Tamoxifen Inducible Cre", href: "/tamoxifen-inducible-cre" }
];

const projectResources = [
  { title: "FAQs", href: "/faqs" },
  { title: "Technologies", href: "/technologies" }
];

// FAQ Data
const getFaqData = () => [
  {
    question: "What is the difference between transgenic and knockin models?",
    answer: (
      <>
        Transgenic models introduce exogenous DNA sequences through random integration (<GlossaryTermLink term="pronuclear-injection">pronuclear injection</GlossaryTermLink>) or targeted insertion at <GlossaryTermLink term="safe-harbor-locus">safe-harbor loci</GlossaryTermLink> (<GlossaryTermLink term="rosa26-locus">ROSA26</GlossaryTermLink>). <GlossaryTermLink term="knockin-mouse-models">Knockin models</GlossaryTermLink> modify endogenous gene loci through <GlossaryTermLink term="homologous-recombination">homologous recombination</GlossaryTermLink>. Transgenics add new genetic elements; knockins modify existing genes at their native locations.
      </>
    )
  },
  {
    question: "When should I use conventional transgenesis vs ROSA26 targeting?",
    answer: (
      <>
        Use conventional transgenesis for rapid generation, multiple founder lines for comparison, or when high expression levels are desired. Use <GlossaryTermLink term="rosa26-locus">ROSA26 targeting</GlossaryTermLink> for <GlossaryTermLink term="single-copy-integration">single-copy integration</GlossaryTermLink> at a defined location, predictable expression patterns, or when position effects must be avoided. ROSA26 provides more consistent expression across generations.
      </>
    )
  },
  {
    question: "What is BAC transgenesis and when is it used?",
    answer: (
      <>
        <GlossaryTermLink term="large-fragment-bac-targeting">BAC (bacterial artificial chromosome) transgenesis</GlossaryTermLink> uses large genomic fragments (100-200 kb) including the gene of interest with native <GlossaryTermLink term="promoter-enhancer-regulatory-element">regulatory elements</GlossaryTermLink>. BAC transgenics show more physiological expression patterns than conventional transgenics because distant enhancers and regulatory regions are preserved. BAC transgenesis is particularly valuable for generating <GlossaryTermLink term="cre-driver-line">Cre driver lines</GlossaryTermLink>.
      </>
    )
  },
  {
    question: "Can transgenic models be used for conditional expression?",
    answer: (
      <>
        Yes. Transgenic models can incorporate conditional expression cassettes including <GlossaryTermLink term="lox-stop-lox-cassette">LoxP-stop-LoxP</GlossaryTermLink> for Cre-dependent expression, <GlossaryTermLink term="tet-on-tet-off-systems">TRE-driven systems</GlossaryTermLink> for doxycycline control, or other inducible systems. ROSA26-targeted transgenics are commonly used for conditional <GlossaryTermLink term="reporter-gene-reporter-allele">reporter</GlossaryTermLink> or Cre expression.
      </>
    )
  }
];

export default function TransgenicMouseServicePage() {
  const heroRef = useRef<HTMLDivElement>(null);
  
  useEffect(() => {
    const loadGSAP = async () => {
      const { gsap } = await import('gsap');
      const { ScrollTrigger } = await import('gsap/ScrollTrigger');
      gsap.registerPlugin(ScrollTrigger);
      
      if (heroRef.current) {
        const heroElements = heroRef.current.querySelectorAll('.hero-animate');
        gsap.fromTo(heroElements,
          { opacity: 0, y: 30 },
          { opacity: 1, y: 0, duration: 0.8, stagger: 0.15, ease: 'power2.out' }
        );
      }
      
      const animatedElements = document.querySelectorAll('.animate-in');
      animatedElements.forEach((el) => {
        gsap.fromTo(el,
          { opacity: 0, y: 40 },
          {
            opacity: 1,
            y: 0,
            duration: 0.8,
            ease: 'power2.out',
            scrollTrigger: {
              trigger: el,
              start: 'top 85%',
              toggleActions: 'play none none none'
            }
          }
        );
      });
    };
    
    loadGSAP();
  }, []);

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
      <UXUIDCNavigation />
      
      <main id="main-content">
        {/* Hero Section */}
        <section 
          ref={heroRef}
          style={{
            background: 'linear-gradient(135deg, #0a253c 0%, #1a4a6e 50%, #008080 100%)',
            padding: '80px 20px 60px',
            position: 'relative',
            overflow: 'hidden'
          }}
        >
          <div style={{
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            opacity: 0.1,
            backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.4'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`
          }} />
          
          <div style={{ maxWidth: '1000px', margin: '0 auto', position: 'relative' }}>
            <div>
              <div 
                className="hero-animate"
                style={{
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '8px',
                  backgroundColor: 'rgba(255,255,255,0.15)',
                  padding: '6px 16px',
                  borderRadius: '20px',
                  marginBottom: '20px'
                }}
              >
                <IconDNA size={16} color="white" />
                <span style={{ color: 'white', fontSize: '.8rem', fontWeight: 500 }}>{heroData.badge}</span>
              </div>
              
              <h1 
                className="hero-animate"
                style={{
                  color: 'white',
                  fontFamily: 'Poppins, sans-serif',
                  fontSize: '2.8rem',
                  fontWeight: 700,
                  lineHeight: 1.1,
                  marginBottom: '20px'
                }}
              >
                {heroData.title}
              </h1>
              
              <p 
                className="hero-animate"
                style={{
                  color: 'rgba(255,255,255,0.9)',
                  fontSize: '1rem',
                  fontWeight: 400,
                  lineHeight: '1.7rem',
                  marginBottom: '15px',
                  maxWidth: '800px'
                }}
              >
                {heroData.intro}
              </p>
              
              <p 
                className="hero-animate"
                style={{
                  color: 'rgba(255,255,255,0.85)',
                  fontSize: '.9rem',
                  fontWeight: 400,
                  lineHeight: '1.6rem',
                  marginBottom: '25px',
                  maxWidth: '800px'
                }}
              >
                {heroData.description}
              </p>
              
              <div className="hero-animate flex flex-wrap gap-4">
                <Link 
                  href="/request-quote"
                  className="inline-flex items-center gap-2 transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
                  style={{
                    backgroundColor: 'white',
                    color: '#0a253c',
                    padding: '10px 20px',
                    minWidth: '160px',
                    fontSize: '.85rem',
                    fontWeight: 500
                  }}
                >
                  <span>Request a Quote</span>
                  <span>→</span>
                </Link>
                <Link 
                  href="/contact"
                  className="inline-flex items-center gap-2 transition-all duration-300 hover:-translate-y-1 hover:shadow-md"
                  style={{
                    backgroundColor: 'transparent',
                    color: 'white',
                    padding: '10px 20px',
                    minWidth: '160px',
                    border: '2px solid white',
                    fontSize: '.85rem',
                    fontWeight: 500
                  }}
                >
                  <span>Talk to a Scientist</span>
                  <span>→</span>
                </Link>
              </div>
            </div>
          </div>
        </section>

        {/* Stats Bar */}
        <section style={{ backgroundColor: '#0a253c', padding: '30px 20px' }}>
          <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              {statsData.map((stat, index) => (
                <div key={index} className="text-center">
                  <div style={{ color: '#008080', fontFamily: 'Poppins, sans-serif', fontSize: '2rem', fontWeight: 700 }}>
                    <UXUIDCAnimatedCounter end={stat.value} suffix={stat.suffix} />
                  </div>
                  <div style={{ color: 'rgba(255,255,255,0.7)', fontSize: '.85rem' }}>{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ITL Offers */}
        <section style={{ backgroundColor: 'white', padding: '60px 20px' }}>
          <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
            <p className="animate-in" style={{ color: '#555', fontSize: '.95rem', lineHeight: '1.7rem', marginBottom: '20px' }}>
              ingenious targeting laboratory offers targeted transgenic approaches using ROSA26 and other safe harbor loci, providing options matched to your experimental requirements.
            </p>
          </div>
        </section>

        {/* Transgenic Approaches */}
        <section style={{ backgroundColor: '#f8f9fa', padding: '60px 20px' }}>
          <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
            <h2 className="animate-in" style={{ color: '#2384da', fontFamily: 'Poppins, sans-serif', fontSize: '2rem', fontWeight: 700, marginBottom: '30px' }}>
              Transgenic Approaches
            </h2>
            
            <div className="grid grid-cols-1 gap-6">
              {transgenicApproaches.map((approach, index) => (
                <div 
                  key={index}
                  className="animate-in group cursor-pointer transition-all duration-300 hover:shadow-lg hover:-translate-y-1"
                  style={{
                    backgroundColor: 'white',
                    padding: '30px',
                    borderRadius: '8px',
                    borderLeft: '4px solid #008080'
                  }}
                >
                  <h3 style={{ color: '#0a253c', fontFamily: 'Poppins, sans-serif', fontSize: '1.2rem', fontWeight: 600, marginBottom: '12px' }}>
                    {approach.title}
                  </h3>
                  <p style={{ color: '#555', fontSize: '.95rem', lineHeight: '1.7rem', marginBottom: '12px' }}>
                    {approach.description}
                  </p>
                  {approach.useCase && (
                    <p style={{ color: '#666', fontSize: '.9rem', lineHeight: '1.6rem', fontStyle: 'italic' }}>
                      {approach.useCase}
                    </p>
                  )}
                  {approach.link && (
                    <Link
                      href={approach.link}
                      className="inline-flex items-center gap-2 transition-colors duration-300 mt-3"
                      style={{ color: '#008080', fontSize: '.85rem', fontWeight: 500 }}
                    >
                      <span>Learn more about ROSA26</span>
                      <IconChevronRight size={14} color="#008080" />
                    </Link>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Applications */}
        <section style={{ backgroundColor: 'white', padding: '60px 20px' }}>
          <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
            <h2 className="animate-in" style={{ color: '#2384da', fontFamily: 'Poppins, sans-serif', fontSize: '2rem', fontWeight: 700, marginBottom: '30px' }}>
              Applications
            </h2>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {applicationsData.map((app, index) => (
                <div 
                  key={index}
                  className="animate-in group cursor-pointer transition-all duration-300 hover:shadow-lg hover:-translate-y-1"
                  style={{
                    backgroundColor: '#f8f9fa',
                    padding: '25px',
                    borderRadius: '8px',
                    borderTop: '4px solid #008080'
                  }}
                >
                  <h3 style={{ color: '#0a253c', fontFamily: 'Poppins, sans-serif', fontSize: '1.1rem', fontWeight: 600, marginBottom: '12px' }}>
                    {app.title}
                  </h3>
                  <p style={{ color: '#555', fontSize: '.9rem', lineHeight: '1.6rem', marginBottom: '12px' }}>
                    {app.description}
                  </p>
                  {app.systems && (
                    <div className="space-y-2 mb-3">
                      {app.systems.map((system, idx) => (
                        <div 
                          key={idx}
                          style={{
                            backgroundColor: 'white',
                            padding: '10px 12px',
                            borderRadius: '4px',
                            borderLeft: '2px solid #2384da'
                          }}
                        >
                          <span style={{ color: '#0a253c', fontWeight: 600, fontSize: '.85rem' }}>{system.name}:</span>
                          <span style={{ color: '#666', fontSize: '.85rem', marginLeft: '5px' }}>{system.desc}</span>
                        </div>
                      ))}
                    </div>
                  )}
                  {app.link && (
                    <Link
                      href={app.link}
                      className="inline-flex items-center gap-2 transition-colors duration-300"
                      style={{ color: '#008080', fontSize: '.85rem', fontWeight: 500 }}
                    >
                      <span>Learn more</span>
                      <IconChevronRight size={14} color="#008080" />
                    </Link>
                  )}
                </div>
              ))}
            </div>

            <p className="animate-in" style={{ color: '#555', fontSize: '.9rem', lineHeight: '1.6rem', marginTop: '25px', fontStyle: 'italic' }}>
              Inducible transgenics enable temporal control over gene expression for studying acute effects and adult onset phenotypes.
            </p>
          </div>
        </section>

        {/* Technical Considerations */}
        <section style={{ backgroundColor: '#008080', padding: '60px 20px' }}>
          <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
            <h2 className="animate-in" style={{ color: 'white', fontFamily: 'Poppins, sans-serif', fontSize: '2rem', fontWeight: 700, marginBottom: '20px' }}>
              Technical Considerations
            </h2>
            <h3 className="animate-in" style={{ color: 'rgba(255,255,255,0.95)', fontFamily: 'Poppins, sans-serif', fontSize: '1.2rem', fontWeight: 600, marginBottom: '20px' }}>
              Targeted Integration Advantages
            </h3>
            <p className="animate-in" style={{ color: 'rgba(255,255,255,0.9)', fontSize: '.95rem', marginBottom: '25px' }}>
              ROSA26 and other targeted approaches provide:
            </p>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {targetedAdvantages.map((advantage, index) => (
                <div 
                  key={index}
                  className="animate-in"
                  style={{
                    backgroundColor: 'rgba(255,255,255,0.1)',
                    padding: '15px 20px',
                    borderRadius: '6px',
                    display: 'flex',
                    alignItems: 'center',
                    gap: '12px'
                  }}
                >
                  <IconCheckCircle size={18} color="white" style={{ flexShrink: 0 }} />
                  <span style={{ color: 'rgba(255,255,255,0.95)', fontSize: '.9rem' }}>{advantage}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Publications Section */}
        <section style={{ backgroundColor: '#f8f9fa', padding: '60px 20px' }}>
          <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
            <h2 className="animate-in" style={{ color: '#2384da', fontFamily: 'Poppins, sans-serif', fontSize: '2rem', fontWeight: 700, marginBottom: '10px' }}>
              Selected Publications
            </h2>
            <p className="animate-in" style={{ color: '#555', fontSize: '.95rem', marginBottom: '30px' }}>
              Rosa26 models generated by ingenious targeting laboratory:
            </p>
            
            <div className="grid grid-cols-1 gap-4">
              {publicationsData.map((pub, index) => (
                <div
                  key={index}
                  className="animate-in group cursor-pointer transition-all duration-300 hover:shadow-lg hover:-translate-y-1"
                  style={{
                    backgroundColor: 'white',
                    padding: '25px',
                    borderRadius: '8px',
                    borderLeft: '4px solid #2384da'
                  }}
                >
                  <p style={{ color: '#555', fontSize: '.85rem', marginBottom: '8px' }}>
                    <span style={{ color: '#0a253c', fontWeight: 500 }}>{pub.authors}</span> ({pub.year}).
                  </p>
                  {pub.link ? (
                    <a
                      href={pub.link}
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{
                        display: 'block',
                        fontSize: '.95rem',
                        color: '#008080',
                        fontWeight: 600,
                        marginBottom: '8px',
                        lineHeight: '1.5',
                        textDecoration: 'none'
                      }}
                      onMouseOver={(e) => (e.currentTarget.style.textDecoration = 'underline')}
                      onMouseOut={(e) => (e.currentTarget.style.textDecoration = 'none')}
                    >
                      {pub.title} ↗
                    </a>
                  ) : (
                    <p style={{ fontSize: '.95rem', color: '#333', fontWeight: 600, marginBottom: '8px', lineHeight: '1.5' }}>
                      {pub.title}
                    </p>
                  )}
                  <p style={{ color: '#666', fontSize: '.85rem', fontStyle: 'italic' }}>
                    <em>{pub.journal}</em>
                    {pub.volume && <span style={{ fontStyle: 'normal' }}> {pub.volume}</span>}
                  </p>
                </div>
              ))}
            </div>
            
            <div className="animate-in text-center" style={{ marginTop: '25px' }}>
              <Link 
                href="/publications"
                className="inline-flex items-center gap-2 transition-all duration-300 hover:-translate-y-1 hover:shadow-md"
                style={{
                  backgroundColor: '#2384da',
                  color: 'white',
                  padding: '10px 25px',
                  borderRadius: '4px',
                  fontSize: '.85rem',
                  fontWeight: 500
                }}
              >
                <span>View All Publications</span>
                <IconChevronRight size={16} color="white" />
              </Link>
            </div>
          </div>
        </section>

        {/* Testimonials Section */}
        <section style={{ backgroundColor: '#f7f7f7', padding: '60px 20px' }}>
          <div style={{ maxWidth: testimonials.length === 1 ? '900px' : '1100px', margin: '0 auto', width: '100%' }}>
            <h2 className="animate-in" style={{ textAlign: 'center', color: '#2384da', fontFamily: 'Poppins, sans-serif', fontSize: '2rem', fontWeight: 700, marginBottom: '40px' }}>
              What Researchers Say
            </h2>
            <div style={{ display: testimonials.length === 1 ? 'block' : 'grid', gridTemplateColumns: testimonials.length === 2 ? 'repeat(2, 1fr)' : testimonials.length >= 3 ? 'repeat(3, 1fr)' : undefined, gap: '24px' }}>
              {testimonials.map((testimonial, index) => (
                <div
                  key={index}
                  className="animate-in"
                  style={{
                    backgroundColor: '#ffffff',
                    border: '1px solid #e0e0e0',
                    borderRadius: '8px',
                    padding: testimonials.length === 1 ? '48px 56px' : '30px',
                    display: 'flex',
                    flexDirection: 'column',
                    transition: 'all 0.3s ease',
                    width: '100%',
                    boxSizing: 'border-box',
                    textAlign: testimonials.length === 1 ? 'center' : 'left',
                  }}
                >
                  <IconQuote size={24} color="#008080" style={{ marginBottom: '15px', ...(testimonials.length === 1 ? { display: 'block', margin: '0 auto 15px' } : {}) }} />
                  <p style={{
                    color: '#666',
                    fontFamily: 'Lato, sans-serif',
                    fontSize: testimonials.length === 1 ? '1.1rem' : '.9rem',
                    fontWeight: 400,
                    lineHeight: 1.6,
                    fontStyle: 'italic',
                    marginBottom: '20px',
                    flex: testimonials.length > 1 ? 1 : undefined,
                  }}>
                    &ldquo;{testimonial.quote}&rdquo;
                  </p>
                  <div style={{ marginTop: testimonials.length > 1 ? 'auto' : undefined }}>
                    <p style={{ color: '#333', fontFamily: 'Poppins, sans-serif', fontSize: '.9rem', fontWeight: 600, marginBottom: '5px' }}>
                      — {testimonial.name}
                    </p>
                    <p style={{ color: '#666', fontFamily: 'Lato, sans-serif', fontSize: '.8rem', fontWeight: 400 }}>
                      {testimonial.affiliation}
                    </p>
                  </div>
                </div>
              ))}
            </div>
            <div className="animate-in" style={{ textAlign: 'center', marginTop: '30px' }}>
              <Link
                href="/testimonials"
                className="inline-flex items-center gap-2 transition-colors duration-300"
                style={{ color: '#008080', fontSize: '.9rem', fontWeight: 500 }}
              >
                <span>Read more testimonials</span>
                <IconChevronRight size={16} color="#008080" />
              </Link>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section style={{ backgroundColor: '#0a253c', padding: '60px 20px' }}>
          <div style={{ maxWidth: '800px', margin: '0 auto', textAlign: 'center' }}>
            <h2 className="animate-in" style={{ color: 'white', fontFamily: 'Poppins, sans-serif', fontSize: '2rem', fontWeight: 700, marginBottom: '15px' }}>
              Start Your Transgenic Project
            </h2>
            <p className="animate-in" style={{ color: 'rgba(255,255,255,0.85)', fontSize: '.95rem', lineHeight: '1.7rem', marginBottom: '30px' }}>
              Our scientific consultants are ready to discuss your research requirements and optimal targeted transgenic approach for your experimental goals. Initial consultation is provided at no charge and includes construct design review, approach recommendations, timeline, and price estimate.
            </p>
            <div className="animate-in flex flex-wrap justify-center gap-4">
              <Link 
                href="/request-quote"
                className="inline-flex items-center gap-2 transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
                style={{
                  backgroundColor: '#008080',
                  color: 'white',
                  padding: '12px 30px',
                  fontSize: '.9rem',
                  fontWeight: 500
                }}
              >
                <span>Request a Quote</span>
                <span>→</span>
              </Link>
              <Link 
                href="/contact"
                className="inline-flex items-center gap-2 transition-all duration-300 hover:-translate-y-1 hover:shadow-md"
                style={{
                  backgroundColor: 'transparent',
                  color: 'white',
                  padding: '12px 30px',
                  border: '2px solid white',
                  fontSize: '.9rem',
                  fontWeight: 500
                }}
              >
                <span>Free Consultation</span>
                <span>→</span>
              </Link>
            </div>
          </div>
        </section>

        {/* Lab Signals Newsletter CTA */}
        <section style={{ backgroundColor: '#f7f7f7', padding: '60px 20px' }}>
          <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
            <LabSignalsSignup 
              variant="banner"
              title="Transgenic Design Insights"
              description="Subscribe to Lab Signals for expert guides on BAC transgenics, ROSA26 targeting, and Cre driver design from our PhD scientists."
            />
          </div>
        </section>

        {/* FAQ Section */}
        <section style={{ backgroundColor: 'white', padding: '60px 20px' }}>
          <div style={{ maxWidth: '800px', margin: '0 auto' }}>
            <h2 className="animate-in" style={{ color: '#2384da', fontFamily: 'Poppins, sans-serif', fontSize: '2rem', fontWeight: 700, marginBottom: '30px', textAlign: 'center' }}>
              Frequently Asked Questions
            </h2>
            <div className="animate-in">
              <UXUIDCAnimatedFAQ faqs={getFaqData()} />
            </div>
          </div>
        </section>

        {/* Related Links Section */}
        <section style={{ backgroundColor: '#f8f9fa', padding: '60px 20px' }}>
          <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
              <div className="animate-in">
                <h3 style={{ color: '#0a253c', fontFamily: 'Poppins, sans-serif', fontSize: '1rem', fontWeight: 600, marginBottom: '15px' }}>
                  Transgenic Services
                </h3>
                <ul style={{ listStyle: 'none', padding: 0 }}>
                  {transgenicServices.map((link, index) => (
                    <li key={index} style={{ marginBottom: '10px' }}>
                      <Link 
                        href={link.href}
                        className="inline-flex items-center gap-2 transition-colors duration-300 hover:text-teal-600"
                        style={{ color: '#2384da', fontSize: '.85rem' }}
                      >
                        <IconChevronRight size={12} color="#2384da" />
                        <span>{link.title}</span>
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
              
              <div className="animate-in">
                <h3 style={{ color: '#0a253c', fontFamily: 'Poppins, sans-serif', fontSize: '1rem', fontWeight: 600, marginBottom: '15px' }}>
                  Related Model Types
                </h3>
                <ul style={{ listStyle: 'none', padding: 0 }}>
                  {relatedModelTypes.map((link, index) => (
                    <li key={index} style={{ marginBottom: '10px' }}>
                      <Link 
                        href={link.href}
                        className="inline-flex items-center gap-2 transition-colors duration-300 hover:text-teal-600"
                        style={{ color: '#2384da', fontSize: '.85rem' }}
                      >
                        <IconChevronRight size={12} color="#2384da" />
                        <span>{link.title}</span>
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
              
              <div className="animate-in">
                <h3 style={{ color: '#0a253c', fontFamily: 'Poppins, sans-serif', fontSize: '1rem', fontWeight: 600, marginBottom: '15px' }}>
                  Related Technologies
                </h3>
                <ul style={{ listStyle: 'none', padding: 0 }}>
                  {relatedTechnologies.map((link, index) => (
                    <li key={index} style={{ marginBottom: '10px' }}>
                      <Link 
                        href={link.href}
                        className="inline-flex items-center gap-2 transition-colors duration-300 hover:text-teal-600"
                        style={{ color: '#2384da', fontSize: '.85rem' }}
                      >
                        <IconChevronRight size={12} color="#2384da" />
                        <span>{link.title}</span>
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
              
              <div className="animate-in">
                <h3 style={{ color: '#0a253c', fontFamily: 'Poppins, sans-serif', fontSize: '1rem', fontWeight: 600, marginBottom: '15px' }}>
                  Project Resources
                </h3>
                <ul style={{ listStyle: 'none', padding: 0 }}>
                  {projectResources.map((link, index) => (
                    <li key={index} style={{ marginBottom: '10px' }}>
                      <Link 
                        href={link.href}
                        className="inline-flex items-center gap-2 transition-colors duration-300 hover:text-teal-600"
                        style={{ color: '#2384da', fontSize: '.85rem' }}
                      >
                        <IconChevronRight size={12} color="#2384da" />
                        <span>{link.title}</span>
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>
      </main>
      
      <UXUIDCFooter />
      
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Service",
            "name": "Transgenic Mouse Models",
            "provider": {
              "@type": "Organization",
              "name": "ingenious targeting laboratory"
            },
            "description": "Custom transgenic mouse models for overexpression, Cre drivers, and reporter lines. BAC transgenic and ROSA26 targeted approaches. 2,500+ projects since 1998.",
            "serviceType": "Transgenic Mouse Model Generation"
          })
        }}
      />
    </div>
  );
}
