/**
 * Verified Publications Database
 * 
 * This file contains verified publications featuring ITL (ingenious targeting laboratory) 
 * mouse models. All entries have been verified against PubMed.
 * 
 * IMPORTANT: Only add publications that:
 * 1. Used mouse models generated by ITL
 * 2. Have been verified on PubMed
 * 3. Include the correct PMID
 * 
 * HOW TO VERIFY A PUBLICATION:
 * 1. Search PubMed: https://pubmed.ncbi.nlm.nih.gov/
 * 2. Verify the title, authors, journal, and year match
 * 3. Check the Methods/Acknowledgments for ITL mention
 * 4. Add the PMID to the link field
 */

export interface VerifiedPublication {
  authors: string;
  year: string | number;
  title: string;
  journal: string;
  volume?: string;
  link: string;  // PubMed URL
  pmid: string;  // PubMed ID for reference
  categories: string[];  // e.g., ['neuroscience', 'alzheimers']
}

// Core verified publications - these appear on the main publications page
export const verifiedPublications: VerifiedPublication[] = [
  // 2024-2025 Publications
  {
    authors: "Chakrabarti S et al.",
    year: "2024",
    title: "Touch sensation requires the mechanically gated ion channel ELKIN1.",
    journal: "Science",
    volume: "383(6686): 992-998",
    link: "https://pubmed.ncbi.nlm.nih.gov/38422143/",
    pmid: "38422143",
    categories: ["neuroscience", "sensory"]
  },
  {
    authors: "Mlynarczyk C et al.",
    year: "2023",
    title: "BTG1 mutation yields supercompetitive B cells primed for malignant transformation.",
    journal: "Science",
    volume: "379(6629): eabj0412",
    link: "https://pubmed.ncbi.nlm.nih.gov/36656933/",
    pmid: "36656933",
    categories: ["oncology", "immunology"]
  },
  {
    authors: "Vacher CM et al.",
    year: "2021",
    title: "Placental endocrine function shapes cerebellar development and social behavior.",
    journal: "Nature Neuroscience",
    volume: "24(10): 1392-1401",
    link: "https://pubmed.ncbi.nlm.nih.gov/34400844/",
    pmid: "34400844",
    categories: ["neuroscience", "development"]
  },
  
  // Classic/Foundational Publications
  {
    authors: "Clausen BE et al.",
    year: "1999",
    title: "Conditional gene targeting in macrophages and granulocytes using LysMcre mice.",
    journal: "Transgenic Research",
    volume: "8(4): 265-277",
    link: "https://pubmed.ncbi.nlm.nih.gov/10621974/",
    pmid: "10621974",
    categories: ["immunology", "cre-lox", "methods"]
  },

  // Cardiovascular
  {
    authors: "Xiao Y et al.",
    year: "2025",
    title: "The innate immune receptor NLRX1 is a novel required modulator for mPTP opening: implications for cardioprotection.",
    journal: "Basic Research in Cardiology",
    volume: "120(4): 617-634",
    link: "https://pubmed.ncbi.nlm.nih.gov/40536683/",
    pmid: "40536683",
    categories: ["cardiovascular", "cardioprotection"]
  },
];

/**
 * Get publications by category
 */
export function getPublicationsByCategory(category: string): VerifiedPublication[] {
  return verifiedPublications.filter(pub => 
    pub.categories.includes(category.toLowerCase())
  );
}

/**
 * Get publications by multiple categories (OR logic)
 */
export function getPublicationsByCategories(categories: string[]): VerifiedPublication[] {
  const lowerCategories = categories.map(c => c.toLowerCase());
  return verifiedPublications.filter(pub => 
    pub.categories.some(cat => lowerCategories.includes(cat))
  );
}

/**
 * Search publications by author, title, or journal
 */
export function searchPublications(query: string): VerifiedPublication[] {
  const lowerQuery = query.toLowerCase();
  return verifiedPublications.filter(pub =>
    pub.authors.toLowerCase().includes(lowerQuery) ||
    pub.title.toLowerCase().includes(lowerQuery) ||
    pub.journal.toLowerCase().includes(lowerQuery)
  );
}

// Disease/Area-specific publication collections for individual pages
// These map to specific page needs

export const neurosciencePublications = verifiedPublications.filter(p => 
  p.categories.includes('neuroscience')
);

export const oncologyPublications = verifiedPublications.filter(p => 
  p.categories.includes('oncology')
);

export const immunologyPublications = verifiedPublications.filter(p => 
  p.categories.includes('immunology')
);

export const cardiovascularPublications = verifiedPublications.filter(p => 
  p.categories.includes('cardiovascular')
);

export const methodsPublications = verifiedPublications.filter(p => 
  p.categories.includes('methods') || p.categories.includes('cre-lox')
);
